name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: secure-platform-api

jobs:
  ci:
    name: Test and Build
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        working-directory: app

    steps:
      # Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Install Dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run Tests
      - name: Run Tests
        run: pytest

      # Install Semgrep
      - name: Install Semgrep
        run: pip install semgrep

      # Run Semgrep
      - name: Run Semgrep SAST Scan
        run: |
          semgrep scan \
            --config=auto \
            . || true

      # Configure AWS Credentials (OIDC)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::884538755968:role/GithubActionsECRRole
          aws-region: ${{ env.AWS_REGION }}

      # Login to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build Docker Image
      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./app
          file: ./app/Dockerfile
          load: true
          push: false
          tags: secure-platform-api:latest

      # Trivy Filesystem Scan
      - name: Run Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: ./app
          format: table
          severity: CRITICAL,HIGH
          ignore-unfixed: true
          exit-code: "1"

      # Trivy Image Scan
      - name: Run Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: secure-platform-api:latest
          format: table
          severity: CRITICAL,HIGH
          ignore-unfixed: true
          exit-code: "1"

      # Generate SBOM
      - name: Generate SBOM
        run: |
          trivy image \
            --format cyclonedx \
            --output sbom.json \
            secure-platform-api:latest

      # Upload SBOM
      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: secure-platform-sbom
          path: app/sbom.json

      # Tag Docker Image
      - name: Tag Docker Image
        run: |
          docker tag secure-platform-api:latest \
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

      # Push Docker Image
      - name: Push Docker Image
        run: |
          docker push \
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

      # Install Cosign
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      # Sign Docker Image (Keyless)
      - name: Sign Docker Image
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: |
          cosign sign --yes \
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}