name: Continuous Integration
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    ci:
        name: Test and Build
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: app

        steps:
            # Checkout Repository
            - name: Checkout Repository
              uses: actions/checkout@v4

            # Setup Python
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.12"

            # Install Dependencies
            - name: Install Dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            # Run Unit Tests
            - name: Run Tests
              run: pytest

            # Setup Docker Buildx
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            # Build Docker Image
            - name: Build Docker Image
              uses: docker/build-push-action@v6
              with:
                  context: ./app
                  file: ./app/Dockerfile
                  push: false
                  tags: secure-platform-api:latest

            # Trivy Filesystem Scan
            - name: Run Trivy Filesystem Scan
              uses: aquasecurity/trivy-action@master
              with:
                  scan-type: "fs"
                  scan-ref: "./app"
                  format: "table"
                  severity: "CRITICAL,HIGH"
                  exit-code: "1"
                  ignore-unfixed: true
